### ISSUE TITLE
Moon phase widget

### ISSUE THREAD

**Issue by earthwitch** [oakwoodgates/mtoll#26]
Center title for Badges and Points

**Comment by earthwitch** [comment]
I did it!

But I'm having trouble with the Moon Phase widget-- I want the title to NOT show so I can have a title above like in the other widgets but when I leave it blank it inserts a default

**Comment by earthwitch** [comment]
Look at this now. Not sure we need to do anything because I re-arranged the hub page

**Comment by oakwoodgates** [comment]
Nice, I like it :)

I had the widget on my list, and when I was in dev mode on the staging site, I noticed a few other errors coming from the plugin. It's been 2.5 years since the plugin author updated it...so, I went ahead and incorporated it into this plugin and fixed all the errors.

When I was on his website I saw this and thought I'd share with you - http://www.joeswebtools.com/wordpress-plugins/ephemeris/
